name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Simulate long-running process
        run: sleep 110
